import "@/styles/globals.scss"
import type { ReactNode } from "react"

export const metadata = {
  title: "Chord Church App",
  description: "Generated by create next app"
}

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  )
}
