import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Chord Church App</title>
        <meta name="Church app" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Contenido
      </div>
    </>
  )
}
