import Head from "next/head"
import LoginComponent from "@/components/auth/login-component"

export default function Home() {


  return (
    <>
      <Head>
        <title>Chord Church App</title>
        <meta name="Church app" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/1.png" />
      </Head>
      <LoginComponent  />
    </>
  )
}
